version: '3'
services:
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'b2-paris'

  phpmyadmin:
      image: phpmyadmin
      depends_on:
        - mysql
      ports:
        - 8080:80
      environment:
        PMA_HOST: mysql

volumes:
   db-data: